#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &



# Set workspace names with icons

bspc monitor -d 一 二 三 四 五 六 七 八

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Autostart
sxhkd &
nitrogen --restore &
dunst &
~/.config/polybar/launch.sh &
#~/.config/polybar/hide-on-fullscreen.sh &
picom &

